rem Put this file into the extracted driver folder and execute (double-click) it. 
rem Removal.png (in the Telemetry & Crap free folder) shows your what is safe to remove. 
rd /s /q Display.Optimus
rd /s /q Display.NView
rd /s /q Display.Update
rd /s /q DisplayDriverCrashAnalyzer
rd /s /q GFExperience
rd /s /q GFExperience.NvStreamSrv
rd /s /q GfExperienceService
rd /s /q LEDVisualizer
rd /s /q Miracast.VirtualAudio
rd /s /q MS.NET
rd /s /q MSVCRT
rd /s /q Network.Service
rd /s /q NV3DVision
rd /s /q NV3DVisionUSB.Driver
rd /s /q NvCamera
rd /s /q NvVAD
rd /s /q NvAbHub
rd /s /q NVWMI
rd /s /q NvvHCI
rd /s /q NvContainer
rd /s /q NGXCore
rd /s /q ShadowPlay
rd /s /q ShieldWirelessController
rd /s /q Update.Core
rd /s /q nodejs
rd /s /q NvBackend
rd /s /q NvTelemetry
